import { mdiAlien, mdiBabyFace, mdiBadminton, mdiBaseballBat, mdiBasketball, mdiBat, mdiBikeFast, mdiBilliards, mdiBookOpenVariant, mdiBrain, mdiBrush, mdiCalculatorVariant, mdiCards, mdiCodeTags, mdiCrown, mdiCurrencyUsd, mdiDramaMasks, mdiEmoticon, mdiEmoticonLol, mdiFace, mdiFaceWoman, mdiHeart, mdiMusic, mdiRocket, mdiRugby, mdiSoccer, mdiTennis, mdiYoutube } from "@mdi/js";

export default {
    alien: mdiAlien,
    babyFace: mdiBabyFace,
    badminton: mdiBadminton,
    baseball: mdiBaseballBat,
    basketball: mdiBasketball,
    bat: mdiBat,
    bike: mdiBikeFast,
    billiards: mdiBilliards,
    book: mdiBookOpenVariant,
    brain: mdiBrain,
    brush: mdiBrush,
    math: mdiCalculatorVariant,
    cards: mdiCards,
    code: mdiCodeTags,
    crown: mdiCrown,
    money: mdiCurrencyUsd,
    acting: mdiDramaMasks,
    happy: mdiEmoticon,
    funny: mdiEmoticonLol,
    face: mdiFace,
    faceFemale: mdiFaceWoman,
    heart: mdiHeart,
    music: mdiMusic,
    rocket: mdiRocket,
    rugby: mdiRugby,
    soccer: mdiSoccer,
    tennis: mdiTennis,
    youtube: mdiYoutube,
}