import { mdiAirballoon, mdiAirplane, mdiAllInclusive, mdiAlpha, mdiAnchor, mdiAndroidDebugBridge, mdiBank, mdiBaseballBat, mdiBadminton, mdiBasketball, mdiBeach, mdiBilliards, mdiBoomerang, mdiArmFlex, mdiAtom, mdiBat, mdiBike, mdiBullseyeArrow, mdiBug, mdiBrush, mdiBrain, mdiCactus, mdiBusSchool } from "@mdi/js";

export default {
    airballoon: mdiAirballoon,
    plane: mdiAirplane,
    infinity: mdiAllInclusive,
    alpha: mdiAlpha,
    anchor: mdiAnchor,
    android: mdiAndroidDebugBridge,
    bank: mdiBank,
    badminton: mdiBadminton,
    beach: mdiBeach,
    baseball: mdiBaseballBat,
    basketball: mdiBasketball,
    billiards: mdiBilliards,
    boomerang: mdiBoomerang,
    arm: mdiArmFlex,
    atom: mdiAtom,
    bat: mdiBat,
    bike: mdiBike,
    archery: mdiBullseyeArrow,
    bug: mdiBug,
    brush: mdiBrush,
    brain: mdiBrain,
    cactus: mdiCactus,
    bus: mdiBusSchool,
}